#include <Arduino.h>

#define LEDARRAY_D 2
#define LEDARRAY_C 3
#define LEDARRAY_B 4
#define LEDARRAY_A 5
#define LEDARRAY_G 6
#define LEDARRAY_DI 7
#define LEDARRAY_CLK 8
#define LEDARRAY_LAT 9
#define led 13

const unsigned char data[] =	// Generated by https://www.riyas.org/2013/12/online-led-matrix-font-generator-with.html
{
  0xcf, 0x09, 0xc0, 0x90, 0x69, 0x08, 0x00, 0x90, 0x29, 0x0b, 0xef, 0xf0, 0x2f, 0x48, 0x00, 0x80, 0x29, 0x48, 0x00, 0x40, 0x29, 0x49, 0xe0, 0x40, 0x8f, 0x48, 0x0e, 0x40, 0x69, 0x48, 0x04, 0x40, 0x29, 0x49, 0xe4, 0x40, 0x0f, 0x48, 0x04, 0x40, 0x20, 0x48, 0x04, 0x20, 0x40, 0x49, 0xe4, 0x20, 0x49, 0x49, 0x24, 0x28, 0x89, 0x09, 0x2e, 0x28, 0x89, 0x09, 0xe0, 0x28, 0x80, 0x18, 0x00, 0x10
};

void setup()
{
  pinMode(LEDARRAY_D, OUTPUT); 
  pinMode(LEDARRAY_C, OUTPUT);
  pinMode(LEDARRAY_B, OUTPUT);
  pinMode(LEDARRAY_A, OUTPUT);
  pinMode(LEDARRAY_G, OUTPUT);
  pinMode(LEDARRAY_DI, OUTPUT);
  pinMode(LEDARRAY_CLK, OUTPUT);
  pinMode(LEDARRAY_LAT, OUTPUT);

//  Clear_Display();
}


void loop()
{
  unsigned int i;
  for(i = 0; i < 30; i++) {
    Display(data);
  }
}


void Display(unsigned char *data)
{
  unsigned int i, j;

  for(i = 0; i < 16; i++) {
    digitalWrite(LEDARRAY_G, HIGH);	// Turn off LED
    for(j = 0; j < 4; j++) {
      Send(~(unsigned char)(data[(4-j) + i*4 - 1]));
    }

    digitalWrite(LEDARRAY_LAT, HIGH);	// Latch the data line
    delayMicroseconds(1);
  
    digitalWrite(LEDARRAY_LAT, LOW);
    delayMicroseconds(1);

    Scan_Line(i);
    
    digitalWrite(LEDARRAY_G, LOW);	// Turn on LED
    
    delayMicroseconds(300);		// LED needs some time to get brighter
  } 
}

void Scan_Line(unsigned char m)
{ 
  digitalWrite(LEDARRAY_D, (m & 0x08) >> 3);
  digitalWrite(LEDARRAY_C, (m & 0x04) >> 2);
  digitalWrite(LEDARRAY_B, (m & 0x02) >> 1);
  digitalWrite(LEDARRAY_A, (m & 0x01));
}

void Send(unsigned char dat)
{
  unsigned char i;
  digitalWrite(LEDARRAY_CLK, LOW);
  delayMicroseconds(1);
  digitalWrite(LEDARRAY_LAT, LOW);
  delayMicroseconds(1);

  for(i = 0 ;i < 8 ; i++) {
    digitalWrite(LEDARRAY_DI, dat & 0x01);

    digitalWrite(LEDARRAY_CLK, HIGH);       // Raising edge
    delayMicroseconds(1);
    digitalWrite(LEDARRAY_CLK, LOW);
    delayMicroseconds(1);
    dat >>= 1;
  }     
}
